name: Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - uses: gradle/gradle-build-action@v2.8.0

      - name: Build
        run: gradle build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          folder: build/js/packages/portfolio
          ssh-key: ${{ secrets.DEPLOY_KEY }}
